### ISSUE TITLE
Bug: Wrong number of months produce by Utilities

### ISSUE THREAD

**Issue by umbobabo** [economist-components/react-i13n-omniture#24]
This row of the legacy code produce a wrong output if we are in a similar condition:

`var currDate = new Date('2016/03/31'); var subDate = new Date('2016/04/05');`

We expect that this will produce 'Less_than_1_MO' but what we got is '1MO' due to this calculation:

`var months = subDate.getMonth() - currDate.getMonth() + (12 * (subDate.getFullYear() - currDate.getFullYear()));
           subsRemaining = (months > 0) ? (months + 'MO') : ('Less_than_1_MO');`

https://github.com/economist-components/react-i13n-omniture/blob/master/OmnitureUtils.es6#L98

During the fix, after a chat with the Analytics team, we have to use lower number for the amounts of months remaining for i.e. 1.5 or 1.1 or 1.8 remaining months is expected to output '1MO'.

**Comment by keithamus** [comment]
Sounds like if it is that approximate then you'd be better counting days (or maybe even seconds) and rounding them to rough months. Something as simple as:

```js
var months = Math.floor((subDate - currDate) / 2628000000)
```

**Comment by umbobabo** [comment]
Did you look at my code?
I'm using milliseconds and a 30days long month.

**Comment by keithamus** [comment]
I didn't because I didn't see the reference. Just looked, added some comments.

**Comment by umbobabo** [comment]
Close with PR https://github.com/economist-components/react-i13n-omniture/pull/25
